language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache
env:
    global:
        - PATH: /usr/lib/ccache:$PATH
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    #- "pypy"

install:
    - python setup.py install

script:
    - make test
